name: Add Find And Replace to Rich Editor
description: 'A recipe to manage default findAndReplace button and plugin settings for the Rich Editor with CKEditor 5'
type: optional
install:
  - ckeditor5_plugin_pack_find_and_replace
config:
  actions:
    editor.editor.full_html:
      addItemToToolbar:
        item_name: findAndReplace
