name: Add fullScreen to Rich Editor
description: 'A recipe to manage default fullScreen button and plugin settings for the Rich Editor with CKEditor 5'
type: optional
config:
  actions:
    editor.editor.full_html:
      addItemToToolbar:
        item_name: fullScreen
        position: 17
