name: Add Wrapping to Rich Editor
description: 'A recipe to to add wrapping to the Rich Editor with CKEditor 5'
type: optional
config:
  actions:
    editor.editor.full_html:
      addItemToToolbar:
        item_name: '-'
