name: Varbase Editor - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - anchor_link
  - ace_editor
  - ckeditor_bidi
  - entity_embed
  - blazy
  - slick
  - extlink
  - editor_advanced_link
  - ckeditor_media_embed
  - ckeditor_media_resize
  - edit_media_modal
  - linkit
  - pathologic
  - token
  - token_filter
  - ckeditor5_paste_filter
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_find_and_replace
  - ckeditor5_premium_features
  - ckeditor5_premium_features_fullscreen
  - ckeditor5_premium_features_wproofreader
  - ckeditor5_plugin_pack_free_wproofreader
  - ckeditor_emoji
config:
  import:
    ace_editor: '*'
    pathologic: '*'
    editor_advanced_link: '*'
    ckeditor_media_embed: '*'
    ckeditor_media_resize: '*'
    ckeditor5_paste_filter: '*'
    varbase_editor:
      - filter.format.basic_html
      - filter.format.code_html
      - filter.format.full_html
      - editor.editor.basic_html
      - editor.editor.code_html
      - editor.editor.full_html
      - linkit.linkit_profile.linkit_all_nodes
  actions:
    extlink.settings:
      simpleConfigUpdate:
        extlink_alert_text: ''
        extlink_target: true
    pathologic.settings:
      simpleConfigUpdate:
        protocol_style: 'path'
    user.role.editor:
      grantPermissions:
        - 'use text format basic_html'
        - 'use text format full_html'
    user.role.seo_admin:
      grantPermissions:
        - 'use text format basic_html'
        - 'use text format full_html'
        - 'use text format code_html'
    user.role.content_admin:
      grantPermissions:
        - 'use text format basic_html'
        - 'use text format full_html'
    user.role.site_admin:
      grantPermissions:
        - 'use text format basic_html'
        - 'use text format full_html'
        - 'use text format code_html'
