name: varbase_editor_update_100003
description: 'Issue #3460065: Add CKEditor Plug-in Pack module and enable the fullscreen, find and replace, show blocks, and wproof reader plugins'
type: update
install:
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_find_and_replace
  - ckeditor5_premium_features
  - ckeditor5_premium_features_fullscreen
  - ckeditor5_premium_features_wproofreader
  - ckeditor5_plugin_pack_free_wproofreader
config:
  import:
    ckeditor5_plugin_pack: '*'
    ckeditor5_plugin_pack_find_and_replace: '*'
    ckeditor5_premium_features: '*'
    ckeditor5_premium_features_fullscreen: '*'
    ckeditor5_premium_features_wproofreader: '*'
    ckeditor5_plugin_pack_free_wproofreader: '*'
